name: Publicmna-mlops-sep2025-eq25
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - black
  - flake8
  - isort
  - pytest
  - pip:
    - python-dotenv
    - mkdocs
    - -e .